### ISSUE TITLE
'svnclean' err messages on git?

### ISSUE THREAD

**Issue by wstidolph** [ampf/AMPF#2]
"ant clean" invokes clean-all.sh and generates some suspicious messages:

```
[wstidolph@bunter MPF]$ ant clean
Buildfile: build.xml

javac-clean:

clean-all:
     [exec] The command attribute is deprecated.
     [exec] Please use the executable attribute and nested arg elements.
     [exec] ~/Workspaces/Appscio/MPF/MPF/components/mpf-buf-rdf ~/Workspaces/Appscio/MPF/MPF
     [exec] make: *** No rule to make target `svnclean'.  Stop.
```

**Comment by simontuffs** [comment]
The 'svnclean' message is telling you nothing to clean.  The other messages I've ignored for so long: they're an artefact of our Makefile.am autogenerator (mpf-new-component.sh), and can probably be cleaned up by editing all of the Makefile.am.in files.

**Comment by wstidolph** [comment]
I guessed it was 'nothing to clean' but havnig it be explicitly 'svn' clean is disquieting

**Comment by simontuffs** [comment]
The term 'svnclean' is scattered through the Makefile.am files.  It really means 'repositoryclean' and maybe I'll rename it some day: not worth doing now.
