### ISSUE TITLE
ant build doesn't find opencv (it is installed) and says "successful"

### ISSUE THREAD

**Issue by wstidolph** [ampf/AMPF#5]
Good build of GRDF, then ant in MPF results in:
...
     [exec] checking for OPENCV... no
     [exec] configure: error: you need OpenCV 1.1.0 or earlier development packages installed !
     [exec]   configure failed
     [exec] Error: /home/wstidolph/projects/AMPF/MPF/data-types/mpf-iplimage/autogen.sh failed!
     [exec] Result: 1

javac:
    [mkdir] Created dir: /home/wstidolph/projects/AMPF/MPF/target/classes
    [mkdir] Created dir: /home/wstidolph/projects/AMPF/MPF/target/test-classes
    [javac] Compiling 1 source file to /home/wstidolph/projects/AMPF/MPF/target/classes
    [javac] Compiling 5 source files to /home/wstidolph/projects/AMPF/MPF/target/test-classes
    [javac] Note: /home/wstidolph/projects/AMPF/MPF/junit/src/com/appscio/mpf/junit/AnalyzeValgrind.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.

all:

BUILD SUCCESSFUL

but, yum says opencv _is_ installed:
Package opencv-devel-2.0.0-7.fc13.i686 already installed and latest version
Package opencv-2.0.0-7.fc13.i686 already installed and latest version

environment:
Linux 2.6.33.5-112.fc13.i686.PAE #1 SMP Thu May 27 02:56:20 UTC 2010 i686 i686 i386
gstreamer-plugins-bad-free-devel-docs-0.10.19-1.fc13.i686
gst-inspector-0.3-8.fc12.noarch
gstreamer-plugins-bad-free-devel-0.10.19-1.fc13.i686
gstreamer-plugins-bad-0.10.18-1.fc13.i686
gstreamer-plugins-base-0.10.29-1.fc13.i686
gstream-devel-1.6-4.fc12.i686
gstreamer-devel-0.10.29-1.fc13.i686
gstreamer-java-1.3-3.fc12.i686
gstreamer-plugins-good-0.10.23-1.fc13.i686
gstreamer-rtsp-devel-0.10.5-1.fc13.i686
phonon-backend-gstreamer-4.4.1-2.fc13.i686
gstreamer-0.10.29-1.fc13.i686
gstreamer-tools-0.10.29-1.fc13.i686
gstreamer-plugins-bad-free-extras-0.10.19-1.fc13.i686
PackageKit-gstreamer-plugin-0.6.4-1.fc13.i686
gstreamer-java-javadoc-1.3-3.fc12.i686
gstreamer-plugins-base-devel-0.10.29-1.fc13.i686
gstreamer-rtsp-0.10.5-1.fc13.i686
gstreamer-plugins-ugly-0.10.14-1.fc13.i686
gstreamer-python-0.10.16-1.fc12.i686
gstreamer-ffmpeg-0.10.10-1.fc13.i686
gstreamer-plugins-bad-free-0.10.19-1.fc13.i686
gstream-1.6-4.fc12.i686

**Comment by wstidolph** [comment]
Ah, I see - opencv 1.1 "or earlier" and I have opencv 2

**Comment by gbowles** [comment]
The incorrect "build successful" message is fixed now - I added failonerror="true" to all the exec statements in the MPF and GRDF build scripts.

**Comment by wstidolph** [comment]
As a simple (optimistic) test, I changed the configure.ac to accept opencv 2, but it doesn't compile, looks like some definitions got moved around or something (so I'm going to create a new issue):

In file included from /usr/include/opencv/cxmisc.h:52,
     [exec]                  from /usr/include/opencv/cxcore.hpp:46,
     [exec]                  from /usr/include/opencv/cxcore.h:2123,
     [exec]                  from /usr/include/opencv/cv.h:58,
     [exec]                  from mpf-iplimage.h:10,
     [exec]                  from mpf-iplimage.c:17:
     [exec] /usr/include/opencv/cvconfig.h:119:1: error: "PACKAGE" redefined
     [exec] In file included from mpf-iplimage.c:5:
     [exec] ../config.h:45:1: error: this is the location of the previous definition
     [exec] In file included from /usr/include/opencv/cxmisc.h:52,
     [exec]                  from /usr/include/opencv/cxcore.hpp:46,
     [exec]                  from /usr/include/opencv/cxcore.h:2123,
     [exec]                  from /usr/include/opencv/cv.h:58,
     [exec]                  from mpf-iplimage.h:10,
     [exec]                  from mpf-iplimage.c:17:
     [exec] /usr/include/opencv/cvconfig.h:122:1: error: "PACKAGE_BUGREPORT" redefined
     [exec] In file included from mpf-iplimage.c:5:
     [exec] ../config.h:48:1: error: this is the location of the previous definition
     [exec] In file included from /usr/include/opencv/cxmisc.h:52,
     [exec]                  from /usr/include/opencv/cxcore.hpp:46,
     [exec]                  from /usr/include/opencv/cxcore.h:2123,
     [exec]                  from /usr/include/opencv/cv.h:58,
     [exec]                  from mpf-iplimage.h:10,
     [exec]                  from mpf-iplimage.c:17:
     [exec] /usr/include/opencv/cvconfig.h:125:1: error: "PACKAGE_NAME" redefined
     [exec] In file included from mpf-iplimage.c:5:
     [exec] ../config.h:51:1: error: this is the location of the previous definition
     [exec] In file included from /usr/include/opencv/cxmisc.h:52,
     [exec]                  from /usr/include/opencv/cxcore.hpp:46,
     [exec]                  from /usr/include/opencv/cxcore.h:2123,
     [exec]                  from /usr/include/opencv/cv.h:58,
     [exec]                  from mpf-iplimage.h:10,
     [exec]                  from mpf-iplimage.c:17:
     [exec] /usr/include/opencv/cvconfig.h:128:1: error: "PACKAGE_STRING" redefined
     [exec] In file included from mpf-iplimage.c:5:
     [exec] ../config.h:54:1: error: this is the location of the previous definition
     [exec] In file included from /usr/include/opencv/cxmisc.h:52,
     [exec]                  from /usr/include/opencv/cxcore.hpp:46,
     [exec]                  from /usr/include/opencv/cxcore.h:2123,
     [exec]                  from /usr/include/opencv/cv.h:58,
     [exec]                  from mpf-iplimage.h:10,
     [exec]                  from mpf-iplimage.c:17:
     [exec] /usr/include/opencv/cvconfig.h:131:1: error: "PACKAGE_TARNAME" redefined
     [exec] In file included from mpf-iplimage.c:5:
     [exec] ../config.h:57:1: error: this is the location of the previous definition
     [exec] In file included from /usr/include/opencv/cxmisc.h:52,
     [exec]                  from /usr/include/opencv/cxcore.hpp:46,
     [exec]                  from /usr/include/opencv/cxcore.h:2123,
     [exec]                  from /usr/include/opencv/cv.h:58,
     [exec]                  from mpf-iplimage.h:10,
     [exec]                  from mpf-iplimage.c:17:
     [exec] /usr/include/opencv/cvconfig.h:134:1: error: "PACKAGE_VERSION" redefined
     [exec] In file included from mpf-iplimage.c:5:
     [exec] ../config.h:63:1: error: this is the location of the previous definition
     [exec] In file included from /usr/include/opencv/cxmisc.h:52,
     [exec]                  from /usr/include/opencv/cxcore.hpp:46,
     [exec]                  from /usr/include/opencv/cxcore.h:2123,
     [exec]                  from /usr/include/opencv/cv.h:58,
     [exec]                  from mpf-iplimage.h:10,
     [exec]                  from mpf-iplimage.c:17:
     [exec] /usr/include/opencv/cvconfig.h:145:1: error: "VERSION" redefined
     [exec] In file included from mpf-iplimage.c:5:
     [exec] ../config.h:69:1: error: this is the location of the previous definition
