### ISSUE TITLE
Support using latest OpenCV 

### ISSUE THREAD

**Issue by wstidolph** [ampf/AMPF#6]
Attempting to build on current released Fedora fails because F13 uses OpenCV 2 (the current OpenCV release is 2.1) and the  current MPF source is tied to OpenCV 1.1

**Comment by hogel** [comment]
AMPF at least compiles with OpenCV2 if you modify MPF/data-types/mpf-iplimage/configure.ac,

-PKG_CHECK_MODULES(OPENCV, opencv <= 1.1.0, HAVE_OPENCV=yes, HAVE_OPENCV=no)
+PKG_CHECK_MODULES(OPENCV, opencv, HAVE_OPENCV=yes, HAVE_OPENCV=no)

Unittest shows 2 fails for my installation, but these seem not to be related with OpenCV.

**Comment by wstidolph** [comment]
IIRC Simon did try using a more-recent OpenCV and decided to put that version limit in as a result of his testing, but I don't recall specifics... so, I look forward to hearing how it works out for you before we pull in that change ;) (but it's certainly interesting to me, as I'm advancing to Fedora 16 and I _do_ need media pipelines for a project I'm working on... thanks!)

**Comment by wstidolph** [comment]
Not an issue any more :)
