### ISSUE TITLE
unstated build requirements 'check'

### ISSUE THREAD

**Issue by wstidolph** [ampf/AMPF#7]
env: Fedora 13, updated
Following the MPF/BUILDING.TXT directions

build GRDF fails, not clear what needs to be installed (what is package 'check' ?):
  build-components:
     [exec] The command attribute is deprecated.
     [exec] Please use the executable attribute and nested arg elements.
     [exec] + check for build tools
     [exec]   checking for autoconf >= 2.52 ... found 2.65, ok.
     [exec]   checking for automake >= 1.7 ... found 1.11.1, ok.
     [exec]   checking for libtoolize >= 1.5.0 ... found 2.2.6b, ok.
     [exec]   checking for pkg-config >= 0.8.0 ... found 0.23, ok.
     [exec] + checking for autogen.sh options
     [exec]   This autogen script will automatically run ./configure as:
     [exec]   ./configure --enable-maintainer-mode --enable-debug
     [exec]   To pass any additional options, please specify them on the ./autogen.sh
     [exec]   command line.
     [exec] + running aclocal ...
     [exec] + running libtoolize --copy --force...
     [exec] libtoolize: putting auxiliary files in `.'.
     [exec] libtoolize: copying file`./ltmain.sh'
     [exec] libtoolize: Consider adding `AC_CONFIG_MACRO_DIR([m4])' to configure.ac and
     [exec] libtoolize: rerunning libtoolize, to keep the correct libtool macros in-tree.
     [exec] libtoolize: Consider adding`-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
     [exec] + running autoheader ...
     [exec] + running autoconf ...
     [exec] + running automake -a -c...
     [exec] test/Makefile.am:3: `CFLAGS' is a user variable, you should not override it;
     [exec] test/Makefile.am:3: use`AM_CFLAGS' instead.
     [exec] + running configure ... 
     [exec]   ./configure default flags: --enable-maintainer-mode --enable-debug
     [exec] 
     [exec] configure: WARNING: unrecognized options: --enable-debug
     [exec] checking whether to enable maintainer-specific portions of Makefiles... yes
     [exec] checking for a BSD-compatible install... /usr/bin/install -c
     [exec] checking whether build environment is sane... yes
     [exec] checking for a thread-safe mkdir -p... /bin/mkdir -p
     [exec] checking for gawk... gawk
     [exec] checking whether make sets $(MAKE)... yes
     [exec] checking for gcc... gcc
     [exec] checking whether the C compiler works... yes
     [exec] checking for C compiler default output file name... a.out
     [exec] checking for suffix of executables... 
     [exec] checking whether we are cross compiling... no
     [exec] checking for suffix of object files... o
     [exec] checking whether we are using the GNU C compiler... yes
     [exec] checking whether gcc accepts -g... yes
     [exec] checking for gcc option to accept ISO C89... none needed
     [exec] checking for style of include used by make... GNU
     [exec] checking dependency style of gcc... gcc3
     [exec] checking build system type... x86_64-unknown-linux-gnu
     [exec] checking host system type... x86_64-unknown-linux-gnu
     [exec] checking for a sed that does not truncate output... /bin/sed
     [exec] checking for grep that handles long lines and -e... /bin/grep
     [exec] checking for egrep... /bin/grep -E
     [exec] checking for fgrep... /bin/grep -F
     [exec] checking for ld used by gcc... /usr/bin/ld
     [exec] checking if the linker (/usr/bin/ld) is GNU ld... yes
     [exec] checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
     [exec] checking the name lister (/usr/bin/nm -B) interface... BSD nm
     [exec] checking whether ln -s works... yes
     [exec] checking the maximum length of command line arguments... 1966080
     [exec] checking whether the shell understands some XSI constructs... yes
     [exec] checking whether the shell understands "+="... yes
     [exec] checking for /usr/bin/ld option to reload object files... -r
     [exec] checking for objdump... objdump
     [exec] checking how to recognize dependent libraries... pass_all
     [exec] checking for ar... ar
     [exec] checking for strip... strip
     [exec] checking for ranlib... ranlib
     [exec] checking command to parse /usr/bin/nm -B output from gcc object... ok
     [exec] checking how to run the C preprocessor... gcc -E
     [exec] checking for ANSI C header files... yes
     [exec] checking for sys/types.h... yes
     [exec] checking for sys/stat.h... yes
     [exec] checking for stdlib.h... yes
     [exec] checking for string.h... yes
     [exec] checking for memory.h... yes
     [exec] checking for strings.h... yes
     [exec] checking for inttypes.h... yes
     [exec] checking for stdint.h... yes
     [exec] checking for unistd.h... yes
     [exec] checking for dlfcn.h... yes
     [exec] checking for objdir... .libs
     [exec] checking if gcc supports -fno-rtti -fno-exceptions... no
     [exec] checking for gcc option to produce PIC... -fPIC -DPIC
     [exec] checking if gcc PIC flag -fPIC -DPIC works... yes
     [exec] checking if gcc static flag -static works... no
     [exec] checking if gcc supports -c -o file.o... yes
     [exec] checking if gcc supports -c -o file.o... (cached) yes
     [exec] checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
     [exec] checking whether -lc should be explicitly linked in... no
     [exec] checking dynamic linker characteristics... GNU/Linux ld.so
     [exec] checking how to hardcode library paths into programs... immediate
     [exec] checking whether stripping libraries is possible... yes
     [exec] checking if libtool supports shared libraries... yes
     [exec] checking whether to build shared libraries... yes
     [exec] checking whether to build static libraries... yes
     [exec] checking for pkg-config... /usr/bin/pkg-config
     [exec] checking pkg-config is at least version 0.9.0... yes
     [exec] configure: error: Package requirements (check >= 0.9.4) were not met:
     [exec] 
     [exec] No package 'check' found
     [exec] 
     [exec] Consider adjusting the PKG_CONFIG_PATH environment variable if you
     [exec] installed software in a non-standard prefix.
     [exec] 
     [exec] Alternatively, you may set the environment variables CHECK_CFLAGS
     [exec] and CHECK_LIBS to avoid the need to call pkg-config.
     [exec] See the pkg-config man page for more details.
     [exec] 
     [exec] checking for CHECK...   configure failed
     [exec] Error: /home/wstidolph/Source/AMPF/GRDF/autogen.sh failed!

  BUILD FAILED
  /home/wstidolph/Source/AMPF/GRDF/build.xml:19: exec returned: 1

**Comment by wstidolph** [comment]
it really is the 'check' package ... which, for some reason, didn't show up when I did a yum search... not a GRDF problem

**Comment by gbowles** [comment]
You need check-devel as well, but this should be brought in by gstreamer-devel which is also a requirement.  I updated MPF/BUILDING.TXT to make the requirement for check explicit.
